language: scala
scala:
   - 2.9.1
   
jdk:
   - oraclejdk7
  # - openjdk7
   #- openjdk6
script: sbt 'set resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"' ++$TRAVIS_SCALA_VERSION test

matrix:
 include:
  - jdk: openjdk7
 exclude:
  - jdk: oraclejdk7 
